export const singleBuyData = [
  {
    id: 1,
    product_name: "Wireless Mouse",
    date: "2026-01-01",
    price: "$25",
    status: "Completed",
    buyer_count: 5,
  },
  {
    id: 2,
    product_name: "Mechanical Keyboard",
    date: "2026-01-02",
    price: "$70",
    status: "Active",
    buyer_count: 3,
  },
  {
    id: 3,
    product_name: "Gaming Headset",
    date: "2026-01-03",
    price: "$45",
    status: "Active",
    buyer_count: 2,
  },
  {
    id: 4,
    product_name: "USB-C Hub",
    date: "2026-01-04",
    price: "$30",
    status: "Completed",
    buyer_count: 4,
  },
  {
    id: 5,
    product_name: "Webcam 1080p",
    date: "2026-01-05",
    price: "$55",
    status: "Active",
    buyer_count: 1,
  },
  {
    id: 6,
    product_name: "Laptop Stand",
    date: "2026-01-06",
    price: "$35",
    status: "Completed",
    buyer_count: 6,
  },
  {
    id: 7,
    product_name: "Portable SSD",
    date: "2026-01-07",
    price: "$120",
    status: "Completed",
    buyer_count: 2,
  },
  {
    id: 8,
    product_name: "Monitor 24inch",
    date: "2026-01-08",
    price: "$150",
    status: "Active",
    buyer_count: 1,
  },
  {
    id: 9,
    product_name: "Mouse Pad",
    date: "2026-01-09",
    price: "$10",
    status: "Completed",
    buyer_count: 8,
  },
  {
    id: 10,
    product_name: "Desk Lamp",
    date: "2026-01-10",
    price: "$20",
    status: "Active",
    buyer_count: 3,
  },
  {
    id: 11,
    product_name: "Gaming Chair",
    date: "2026-01-11",
    price: "$200",
    status: "Completed",
    buyer_count: 2,
  },
  {
    id: 12,
    product_name: "Bluetooth Speaker",
    date: "2026-01-12",
    price: "$60",
    status: "Active",
    buyer_count: 4,
  },
  {
    id: 13,
    product_name: "Smartwatch",
    date: "2026-01-13",
    price: "$120",
    status: "Completed",
    buyer_count: 3,
  },
  {
    id: 14,
    product_name: "HDMI Cable",
    date: "2026-01-14",
    price: "$15",
    status: "Active",
    buyer_count: 5,
  },
  {
    id: 15,
    product_name: "External Hard Drive",
    date: "2026-01-15",
    price: "$80",
    status: "Completed",
    buyer_count: 1,
  },
];

export const groupBuyData = [
  {
    id: 101,
    product_name: "Wireless Mouse",
    date: "2026-01-01",
    price: "$20",
    status: "Delivered",
    group_name: "Tech Squad",
    members_count: 5,
  },
  {
    id: 102,
    product_name: "Mechanical Keyboard",
    date: "2026-01-02",
    price: "$60",
    status: "Pending",
    group_name: "Gamers Hub",
    members_count: 8,
  },
  {
    id: 103,
    product_name: "Gaming Headset",
    date: "2026-01-03",
    price: "$40",
    status: "Delivered",
    group_name: "Streamers",
    members_count: 3,
  },
  {
    id: 104,
    product_name: "USB-C Hub",
    date: "2026-01-04",
    price: "$25",
    status: "Cancelled",
    group_name: "Office Crew",
    members_count: 4,
  },
  {
    id: 105,
    product_name: "Webcam 1080p",
    date: "2026-01-05",
    price: "$50",
    status: "Delivered",
    group_name: "Content Creators",
    members_count: 6,
  },
  {
    id: 106,
    product_name: "Laptop Stand",
    date: "2026-01-06",
    price: "$30",
    status: "Pending",
    group_name: "Remote Team",
    members_count: 2,
  },
  {
    id: 107,
    product_name: "Portable SSD",
    date: "2026-01-07",
    price: "$110",
    status: "Delivered",
    group_name: "Designers",
    members_count: 7,
  },
  {
    id: 108,
    product_name: "Monitor 24inch",
    date: "2026-01-08",
    price: "$140",
    status: "Pending",
    group_name: "Coders Unite",
    members_count: 10,
  },
  {
    id: 109,
    product_name: "Mouse Pad",
    date: "2026-01-09",
    price: "$8",
    status: "Delivered",
    group_name: "Office Crew",
    members_count: 4,
  },
  {
    id: 110,
    product_name: "Desk Lamp",
    date: "2026-01-10",
    price: "$18",
    status: "Cancelled",
    group_name: "Gamers Hub",
    members_count: 8,
  },
];
